package gui;
import classes.*;

import classes.databaseConnection;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import javax.swing.JPanel;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mustafakapucu
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
        PreparedStatement pst ;
        Connection conn = databaseConnection.connection();
    
    public Register() {
        initComponents();
        new databaseConnection();
        
    }

  
    class jPanelGradient extends JPanel{
        @Override
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g ;
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(161,255,206); 
            Color color2 = new Color(250,255,209);
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    

    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelGradient();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        s_Name = new javax.swing.JTextField();
        s_Sname = new javax.swing.JTextField();
        s_cCode = new javax.swing.JTextField();
        s_Number = new javax.swing.JTextField();
        s_Mail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        s_Gender = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        utypec = new javax.swing.JComboBox<>();
        s_Password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        snumber = new javax.swing.JTextField();
        Register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setBackground(new java.awt.Color(149, 93, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Sign Up");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 19, 150, -1));

        jSeparator1.setMinimumSize(new java.awt.Dimension(130, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 75, 140, 10));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 91, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 161, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("E-mail");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 299, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Telephone Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 229, 178, -1));

        s_Name.setBorder(null);
        jPanel1.add(s_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 121, 142, 34));

        s_Sname.setBorder(null);
        jPanel1.add(s_Sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 189, 142, 34));

        s_cCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        s_cCode.setText("+90");
        s_cCode.setBorder(null);
        s_cCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_cCodeActionPerformed(evt);
            }
        });
        jPanel1.add(s_cCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 259, 40, 34));

        s_Number.setBorder(null);
        jPanel1.add(s_Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 259, 98, 34));

        s_Mail.setBorder(null);
        jPanel1.add(s_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 329, 142, 34));

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 374, -1, -1));

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 465, -1, -1));

        s_Gender.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        s_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(s_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 497, 142, 34));

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("User Type");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 542, -1, -1));

        utypec.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        utypec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guest", "Student", "Instructor" }));
        utypec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utypecActionPerformed(evt);
            }
        });
        jPanel1.add(utypec, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 574, 142, 34));

        s_Password.setBorder(null);
        jPanel1.add(s_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 418, 142, 34));

        jLabel9.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Student Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 614, -1, -1));
        jLabel9.setVisible(false);

        snumber.setBorder(null);
        jPanel1.add(snumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 646, 142, 32));
        snumber.setVisible(false);

        Register.setBackground(new java.awt.Color(161, 255, 206));
        Register.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        Register.setForeground(new java.awt.Color(0, 51, 102));
        Register.setText("SIGN UP");
        Register.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 204), new java.awt.Color(255, 255, 204)));
        Register.setBorderPainted(false);
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, 178, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 283, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void s_cCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_cCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_cCodeActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed

        if(s_Name.getText().equals("")|| s_Name.getText().equals("")|| s_Number.getText().equals("")){
            JOptionPane.showMessageDialog(null, "THERE IS A PLACE YOU LEFT BLANK");
        }
        else{
        SystemClass.newUser(s_Name, s_Sname, s_cCode, s_Number, s_Mail, s_Password, s_Gender, utypec, snumber);
        this.dispose();
        }
        String recepient=s_Mail.getText();
            try {
                SendGmail.sendMail(recepient);
            } catch (Exception ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        
        
    }//GEN-LAST:event_RegisterActionPerformed

    private void utypecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utypecActionPerformed
        if(utypec.getSelectedItem().equals("Student")){
            jLabel9.setVisible(true);
            snumber.setVisible(true);
        }
        else{
            jLabel9.setVisible(false);
            snumber.setVisible(false);
        }
    }//GEN-LAST:event_utypecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> s_Gender;
    private javax.swing.JTextField s_Mail;
    private javax.swing.JTextField s_Name;
    private javax.swing.JTextField s_Number;
    private javax.swing.JPasswordField s_Password;
    private javax.swing.JTextField s_Sname;
    private javax.swing.JTextField s_cCode;
    private javax.swing.JTextField snumber;
    private javax.swing.JComboBox<String> utypec;
    // End of variables declaration//GEN-END:variables
}
